Volzhanskiy
Step2Victory/LightningTreeUltimate pull request #3
Opened 2023-06-30 20:00 UTC by NikolayVolzhanskiy

2023-07-01 17:09 UTC, Step2Victory requested changes
Набросал комментариев по коду

2023-07-01 17:09 UTC, Step2Victory commented on src/LightningTree.cpp
> +    double _h, double _delta_t, double _r, double _R,
Не надо менять названия переменных. В конструкторе класса разрешается для аргументов использовать имена полей

2023-07-01 17:09 UTC, Step2Victory commented on src/LightningTree.cpp
> +                Phi = vertex.q / (4 * M_PI * epsilon_0) * (1 / (h + r) + 1 / (h + mirror_l + r)) +
Потенциал точки должен суммироваться в цикле. В твоем случае потенциал будет равен вкладу последнего рассмотренного заряда

2023-07-01 17:09 UTC, Step2Victory commented on src/LightningTree.cpp
> +            Phi = vertex.q / (4 * M_PI * epsilon_0) * (1 / (l + r) + 1 / (mirror_l + r)) +
зеркальные заряды берутся с противоположным знаком и нет смысла рассматривать для них отдельно случай когда l < kEps, так как mirrol_l > kEps всегда

2023-07-01 17:09 UTC, Step2Victory commented on src/LightningTree.h
> +#define _USE_MATH_DEFINES
луяше использовать constexpr вместо define. Не очень понял зачем здесь директива _USE_MATH_DEFINES

2023-07-01 17:09 UTC, Step2Victory commented on src/LightningTree.cpp
> +    std::unordered_map<VertexPtr, std::pair<double, double>> delta_charges;
В новой реализации нет смысла в мапе

2023-07-01 17:09 UTC, Step2Victory commented on src/LightningTree.cpp
> +    for (auto& elem : graph)
здесь надо простой пройтись по всем вершинам в графе и перебрать соседей. Посчитать сколько заряда перейдет текущей вершины от каждого соседа (сумма таких зарядов и будет delta q для текущего заряда)

2023-07-01 17:09 UTC, Step2Victory commented on src/LightningTree.cpp
> +    for (auto& elem : delta_charges)
это тоже не нужно

2023-07-01 17:09 UTC, Step2Victory commented on src/LightningTree.cpp
> +                    vertices.push_back(new_vertex);
эту строку перенести под if, а pop_back  убрать

2023-07-03 15:35 UTC, NikolayVolzhanskiy commented on src/LightningTree.cpp
> +    double _h, double _delta_t, double _r, double _R,
Хорошо

2023-07-03 15:36 UTC, NikolayVolzhanskiy commented on src/LightningTree.cpp
> +                Phi = vertex.q / (4 * M_PI * epsilon_0) * (1 / (h + r) + 1 / (h + mirror_l + r)) +
Поправлю

2023-07-03 15:38 UTC, NikolayVolzhanskiy commented on src/LightningTree.cpp
> +            Phi = vertex.q / (4 * M_PI * epsilon_0) * (1 / (l + r) + 1 / (mirror_l + r)) +
Так такой проверки и нет. Проверка только на узлы, а зеркало считается просто за счёт смены знака координаты по оси z

2023-07-03 15:39 UTC, NikolayVolzhanskiy commented on src/LightningTree.h
> +#define _USE_MATH_DEFINES
_USE_MATH_DEFINES для использования констант в библиотеке cmath, хотя можно просто pi прописать.
+ Почему define лучше не использовать?

2023-07-03 15:41 UTC, NikolayVolzhanskiy commented on src/LightningTree.cpp
> +    std::unordered_map<VertexPtr, std::pair<double, double>> delta_charges;
Да я не знаю пока чем заменить это. Может просто вектор из массива с 3я элементами использовать...

2023-07-03 15:41 UTC, NikolayVolzhanskiy commented on src/LightningTree.cpp
> +    for (auto& elem : graph)
это я переписал, только не скинул ещё

2023-07-03 15:42 UTC, NikolayVolzhanskiy commented on src/LightningTree.cpp
> +    for (auto& elem : delta_charges)
дополнительный цикл?
Не совсем понял

2023-07-03 15:44 UTC, NikolayVolzhanskiy commented on src/LightningTree.cpp
> +                    vertices.push_back(new_vertex);
Не. так не получится. У нас же индекс вершины везде фигурирует и если мы вершину не добавим, то её сложно использовать будет. А после всех проверок, если ничего не создалось, просто удаляем вершину, т.к. к ней не ведут ребра

2023-07-03 16:20 UTC, Step2Victory commented on src/LightningTree.cpp
> +            Phi = vertex.q / (4 * M_PI * epsilon_0) * (1 / (l + r) + 1 / (mirror_l + r)) +
Под ифом вклад зеркального заряда должен считаться также как и вне ифа

2023-07-03 16:23 UTC, Step2Victory commented on src/LightningTree.h
> +#define _USE_MATH_DEFINES
В современных стандартах стараются использовать меньше макросов. Им на замену пришли constexpr выражения. Лучше константы использовать так: https://en.cppreference.com/w/cpp/numeric/constants

2023-07-03 16:26 UTC, Step2Victory commented on src/LightningTree.cpp
> +    std::unordered_map<VertexPtr, std::pair<double, double>> delta_charges;
Не надо пытаться заменить. Я использовал эту мапу в своей реализации, так как прям по проходу в цикле считал потенциалы. Тоесть если бы я менял заряд прямо в цикле, то на следующей итерации я бы посчитал потенциал с учетом этого заряда, а надо с учетом старого значения. Сейчас можно прямо в цикле менять заряды, так как потенциалы уже посчитаны заранее

2023-07-03 16:27 UTC, Step2Victory commented on src/LightningTree.cpp
> +    for (auto& elem : delta_charges)
delta_charges не нужны. Делай += в предыдущем цикле

2023-07-03 16:32 UTC, Step2Victory requested changes

2023-07-03 16:32 UTC, Step2Victory commented on src/LightningTree.cpp
> +                    vertices.push_back(new_vertex);
Окей, согласен. Тогда лучше GrowthCriterion(const Vertex&, const Vertex&). Так будет логичнее, так как ребро следует создать, когда критерий выполнен. Если критерий не выполнен, то манипуляции с полями графа производить не надо

2023-07-09 19:40 UTC, Step2Victory commented on src/LightningTree.cpp
> +        point.Phi = Phi + phi_a->getValue(point.coords);
У phi_a нет метода get_value. Вызывай phi_a(point.coords)

2023-07-09 19:40 UTC, Step2Victory commented on src/LightningTree.cpp
>                      LightningTree::Vertex new_vertex = { 0, 0, 0, coords, 0 };
Лучше писать new_vertex = {.q=0, .Q = 0, ,phi = 0, .coords=coords, .grow_iter_number=0}

2023-07-09 19:40 UTC, Step2Victory commented on src/LightningTree.cpp
namespace LightningTree {
...
};

2023-07-09 19:40 UTC, Step2Victory commented on src/LightningTree.cpp
> -                        temp_graph.push_back(CreateNode(vertices.size() - 1), edges.size() - 1, std::vector{i, j, k});
пометить, что vertex_id не перефирийная и grow_less = 0

2023-07-09 19:40 UTC, Step2Victory commented on src/LightningTree.h
> -    size_t periphery_size;
добавить два вектора bool (один для перифирийных, другой для удаленных)

2023-07-09 19:40 UTC, Step2Victory commented on src/LightningTree.h
> +constexpr double PI = 3.14159265358979323846;
#include <numbers>

2023-07-09 19:40 UTC, Step2Victory commented on src/LightningTree.cpp
std::vector<bool> is_perephery;
for (id : vertices) {
    if (DeletionCriteria(id)) {
удалить вершину (пометить удаленной)
}

}

2023-07-09 19:40 UTC, Step2Victory commented on src/LightningTree.cpp
>              Phi += vertex.q / (4 * PI * epsilon_0) * (1 / (l + r) + 1 / (mirror_l + r)) +
здесь тоже заменить pi

2023-07-09 19:40 UTC, Step2Victory commented on src/LightningTree.cpp
> +            size_t graph_id = finde_index(v_id);
что делает finde_index?

2023-07-09 19:40 UTC, Step2Victory commented on src/LightningTree.cpp
> +                        if(vertices[edges[graph[v][i][j][k]].from].growless_iter_number /*Проверка на количество исходящих ребер*/)
growless_iter_number используется только в критерии удаления

2023-07-09 19:40 UTC, Step2Victory commented on src/LightningTree.cpp
> +                        if(vertices[edges[graph[v][i][j][k]].from].growless_iter_number /*Проверка на количество исходящих ребер*/)
здесь надо проверить что степень вершины == 1

2023-07-09 19:40 UTC, Step2Victory commented on src/LightningTree.h
> +    std::vector<bool> edges_activity;
кстати реинкарнация ребер интересный момент. Можно потом спросить у физиков

2023-07-10 12:47 UTC, NikolayVolzhanskiy commented on src/LightningTree.cpp
> +            size_t graph_id = finde_index(v_id);
ищет узел в графе, связанный с индексом вершины, и возвращает его index в векторе.

2023-07-10 12:59 UTC, NikolayVolzhanskiy commented on src/LightningTree.cpp
> +                        if(vertices[edges[graph[v][i][j][k]].from].growless_iter_number /*Проверка на количество исходящих ребер*/)
я подумал использовать этот параметр для 2х критериев. Как количество исходящих ребер у вершины и количество раз, когда из вершины не выросло ребро, только с отрицательным знаком.

2023-07-10 13:06 UTC, NikolayVolzhanskiy commented on src/LightningTree.h
> +    std::vector<bool> edges_activity;
так проще будет реализовать. Если вершины могут вернуться, то и ребра то же, хоть ребра и могут быть из другой вершины, возможность всё равно есть

2023-07-11 16:35 UTC, NikolayVolzhanskiy commented on src/LightningTree.cpp
Ругается на все методы внутри пространства

2023-07-13 17:33 UTC, Step2Victory approved these changes

2023-07-13 17:34 UTC, merged