Update
Step2Victory/LightningTreeUltimate pull request #8
Opened 2023-09-04 18:51 UTC by MADZEROPIE

added gitignore + auto formatted + changed some weird constructions

2023-09-04 19:01 UTC, MADZEROPIE commented on src/ExternalField.h
> +                     std::pow((r_point[2] - l_point[2]), 2));
Abs не нужен

2023-09-04 19:01 UTC, MADZEROPIE commented on src/ExternalField.h
> +        [=, r = start](const std::array<double, 3>& coords) {
move на array всё равно будет копировать

2023-09-04 19:01 UTC, MADZEROPIE commented on src/RandomDirections.h
> -std::uniform_real_distribution<> dis(0, 26);
Перенес в функцию, так как 

- возможен multiple definition, если придется подключать в несколько файлов
- в LightningTree.h уже есть переменные с таким же названием и другим значением.
-  не вижу смысла чтобы оно торчало наружу

2023-09-05 16:02 UTC, Step2Victory requested changes

2023-09-05 16:02 UTC, Step2Victory commented on src/ExternalField.h
> +        [=, r = start](const std::array<double, 3>& coords) {
Захват контекста по значению надо убрать, надо забрать только то, что нужно лямбде для работы. Здесь надо мувнуть potential_values, размер вектора зависит от сетки и может быть довольно большим

2023-09-05 17:53 UTC, Step2Victory approved these changes

2023-09-05 17:54 UTC, merged